channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.0.1
- pip:
  - mlflow==2.22.1
  - cloudpickle==2.2.1
  - numpy==2.2.6
  - pandas==2.3.1
  - psutil==7.0.0
  - scikit-learn==1.7.0
  - scipy==1.15.3
name: mlflow-env
